version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - simple-server
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  simple-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7777:7777
