# version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - simple-server
  simple-server:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - PORT="1234"

    ports:
        - 80:80
