# GitHub action template to upsert a comment on a pull request
name: Upsert Comment
description: Upsert a comment on a pull request
inputs:
  body:
    description: Comment body to upsert
    required: true
  previous_body_includes:
    description: Previous comment body to update. If not provided, a new comment will be created
    required: false
  reactions:
    description: Comma separated list of reactions to add to the comment.
    required: false
  token:
    description: The GitHub token
    required: true
  
runs:
  using: composite
  steps:
    - name: Check for existing comment to update
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: github-actions[bot]
        body-includes: ${{ inputs.previous_body_includes }}

    # Update existing comment and handle errors
    
    - name: Update existing comment matching ${{ inputs.previous_body_includes }}
      uses: peter-evans/create-or-update-comment@v2
      if: steps.fc.outputs.comment-id != 0 
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: ${{ inputs.body }}
        reactions: ${{ inputs.reactions }}
        edit-mode: replace
    
    # Create comment if no existing comment
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      if: steps.fc.outputs.comment-id == 0
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ inputs.body }}
        reactions: ${{ inputs.reactions }} 