trigger: none # Disable CI trigger
pr: 
  branches:
    include:
      - "master"

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: appName
    value: "simple-server"

stages:
  - stage: Build
    displayName: "Build image"
    jobs:
      - job:
        steps:
          - bash: |
              docker build -t ${{ variables.appName }} .
