trigger: none
pr: 
  branches:
    include:
      - "master"

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: appName
    value: "simple-server"
  - name: goVersion
    value: 1.15

stages:
  - stage: Build
    displayName: "Build image"
    jobs:
      - job:
        steps:
          - bash: |
              docker build -t ${{ variables.appName }} .
            
  - stage: Test
    displayName: "Run tests"
    dependsOn: Build // only run if Build succeeded
    jobs:
      - job:
        steps:
          - task: GoTool@0
            inputs:
              version: ${{ variables.goVersion }}
          - task: Go@0
            inputs:
              command: 'test'
          
            