apiVersion: v1
kind: Service
metadata:
  name: simple-server
  labels:
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/instance: simple-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/instance: simple-server
